# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-06 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaportalapp', '0003_auto_20180904_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
