# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-06 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0004_article_user_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dislake',
            new_name='dislike',
        ),
    ]
