# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportalapp', '0005_auto_20180906_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
